title: Keenan Woodall
email: keenanwoodall@gmail.com
description: >- 
baseurl: ""
url: "https://keenanwoodall.com"
google-analytics: UA-119527175-1
twitter_username: keenanwoodall
github_username:  keenanwoodall
youtube_username: keenanwoodall

disqus:
  shortname: keenanwoodall

paginate: 5
paginate_path: posts/page:num/

show_excerpts: true

header_pages:
  - index.html
  - about.md
  - resume.html

defaults:
  -
    scope:
      path: ""
    values:
      comments: false
  -
    scope:
      path: "_posts/tutorials"
    values:
      layout: "post"
      category: "tutorials"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

gems:
  - jekyll-paginate