title: Keenan Woodall
email: keenanwoodall@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://keenanwoodall.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: keenanwoodall
github_username:  keenanwoodall

# Build settings
theme: minima
plugins:
  - jekyll-feed