title: Keenan Woodall
email: keenanwoodall@gmail.com
description: >- 
baseurl: ""
url: "https://keenanwoodall.com"
google-analytics: UA-119527175-1
twitter_username: keenanwoodall
github_username:  keenanwoodall
youtube: keenanwoodall

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

gems:
  - jekyll-paginate

paginate: 10
paginate_path: posts/page:num/